
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Fallback dummy URL lets `prisma generate` (postinstall / CI) run
// without a real database. Real migrations still need DATABASE_URL set.
const databaseUrl =
  process.env.DATABASE_URL ??
  "postgresql://user:password@localhost:5432/yard?sslmode=require";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
