export const CAMPUS_DOMAINS: Record<string, string> = {
  "st.ug.edu.gh": "University of Ghana",
  "ug.edu.gh": "University of Ghana",
  "st.knust.edu.gh": "KNUST",
  "knust.edu.gh": "KNUST",
  "sms.knust.edu.gh": "KNUST",
  "ucc.edu.gh": "UCC",
  "st.ucc.edu.gh": "UCC",
  "live.gctu.edu.gh": "GCTU",
  "gctu.edu.gh": "GCTU",
  "student.gctu.edu.gh": "GCTU",
  "upsamail.edu.gh": "UPSA",
  "uew.edu.gh": "UEW",
  "st.uew.edu.gh": "UEW",
  "uis.edu.gh": "UIS",
  "umds.edu.gh": "UMDS",
  "stu.edu.gh": "STU",
  "tuc.edu.gh": "TUC",
  "atu.edu.gh": "ATU",
  "ktu.edu.gh": "KTU",
  "cktu.edu.gh": "CKTU",
  "aamu.edu.gh": "AAMU",
  "pau.edu.gh": "PAU",
  "dmu.edu.gh": "DMU",
  "uhas.edu.gh": "UHAS",
  "unimac.edu.gh": "UNIMAC",
  "acdi.edu.gh": "ACDI",
  "csir.edu.gh": "CSIR",
  "gims.edu.gh": "GIMS",
  "rims.edu.gh": "RIMS",
  "ips.edu.gh": "IPS",
  "gset.edu.gh": "GSET",
  "nmimt.edu.gh": "NMIMT",
  "gtuc.edu.gh": "GTUC",
  "wiuc.edu.gh": "WIUC",
  "ruc.edu.gh": "RUC",
  "puc.edu.gh": "PUC",
  "cucg.edu.gh": "CUCG",
  "knustford.edu.gh": "KNUSTFORD",
  "bluecrest.edu.gh": "BLUECREST",
  "ipmc.edu.gh": "IPMC",
  "nita.edu.gh": "NITA",
  "gettysburg.edu.gh": "GETTYSBURG",
  "ashtesi.edu.gh": "ASHTESI",
  "gti.edu.gh": "GTI",
  "jppgc.edu.gh": "JPPGC",
  "mmic.edu.gh": "MMIC",
  "ncte.edu.gh": "NCTE",
  "ntc.edu.gh": "NTC",
  "sda.edu.gh": "SDA",
  "tipep.edu.gh": "TIPEP",
  "tset.edu.gh": "TSET",
  "wcsc.edu.gh": "WCSC",
}

export function getCampusFromEmail(email: string): string | null {
  const normalized = email.trim().toLowerCase()
  const atIdx = normalized.lastIndexOf("@")
  if (atIdx === -1) return null
  const domain = normalized.slice(atIdx + 1)
  return CAMPUS_DOMAINS[domain] || null
}